"""Ground truth about this repository, read from the repository.

    python tools/state.py                 # what exists right now
    python tools/state.py --since HEAD~1  # ...and exactly what changed
    python tools/state.py --since <sha>   # ...since any commit

Every number here is computed from `unstated`, from git, or from the filesystem. None of
it is typed by hand, which is the point: a summary written in prose can be wrong by
accident or by motivated reasoning, and this cannot.

**Removals are the reason this exists.** `--since` diffs the catalogue and the ledger
against an earlier commit and prints a loud banner if anything disappeared. On 2026-09-17 a
measured finding was deleted and the owner discovered it by reading a prose summary. That
is the failure this closes: with `--since`, a deletion is a line of output, not something
to be noticed.

Run it and paste its output. Do not retype its numbers.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def sh(*args: str) -> str:
    """Run a command in the repo and return stdout, or "" if it fails."""
    try:
        out = subprocess.run(
            args, cwd=ROOT, capture_output=True, text=True, timeout=180
        )
        return out.stdout.strip()
    except (subprocess.SubprocessError, OSError):
        return ""


def catalogue_at(ref: str | None):
    """Return {key: entry-summary} for a git ref, or for the working tree if ref is None.

    An older commit is loaded by importing its files from a temporary checkout, because the
    dataclass has gained fields over time and parsing the source text would be brittle in
    exactly the direction that hides a removal.
    """
    if ref is None:
        from unstated import CATALOGUE
        from unstated._manifest import ESTABLISHED, HELD_OPEN, WITHDRAWALS

        return (
            {f"{e.library}|{e.component}": e for e in CATALOGUE},
            set(ESTABLISHED),
            {w.key for w in WITHDRAWALS},
            {k for k, _ in HELD_OPEN},
        )

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        if subprocess.run(
            ["git", "worktree", "add", "--detach", tmp, ref],
            cwd=ROOT, capture_output=True, text=True,
        ).returncode != 0:
            return None
        try:
            code = (
                "import sys, json; sys.path.insert(0, %r)\n"
                "try:\n"
                "    from unstated import CATALOGUE\n"
                "except Exception:\n"
                "    print(json.dumps(None)); raise SystemExit\n"
                "try:\n"
                "    from unstated._manifest import ESTABLISHED, HELD_OPEN, WITHDRAWALS\n"
                "except Exception:\n"
                "    ESTABLISHED, HELD_OPEN, WITHDRAWALS = (), (), ()\n"
                "print(json.dumps({\n"
                "  'cat': ['%%s|%%s' %% (e.library, e.component) for e in CATALOGUE],\n"
                "  'est': list(ESTABLISHED),\n"
                "  'wd': [w.key for w in WITHDRAWALS],\n"
                "  'held': [k for k, _ in HELD_OPEN],\n"
                "}))\n" % tmp
            )
            out = subprocess.run(
                [sys.executable, "-c", code], capture_output=True, text=True, cwd=tmp
            ).stdout.strip()
            import json

            data = json.loads(out.splitlines()[-1]) if out else None
            if data is None:
                return None
            return (set(data["cat"]), set(data["est"]), set(data["wd"]), set(data["held"]))
        finally:
            subprocess.run(
                ["git", "worktree", "remove", "--force", tmp],
                cwd=ROOT, capture_output=True,
            )


def section(title: str) -> None:
    print(f"\n{title}")
    print("─" * len(title))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--since", metavar="REF", help="also report what changed since REF")
    ap.add_argument("--run-tests", action="store_true",
                    help="actually run the suite instead of only collecting it")
    args = ap.parse_args()

    from unstated import CATALOGUE
    from unstated._manifest import ESTABLISHED, HELD_OPEN, WITHDRAWALS

    head = sh("git", "rev-parse", "--short", "HEAD")
    branch = sh("git", "rev-parse", "--abbrev-ref", "HEAD")
    dirty = sh("git", "status", "--porcelain")

    print(f"GLOB — repository state   {branch} @ {head}")
    print(f"generated by tools/state.py; every number below is read, not typed")

    # ---------------------------------------------------------------- findings
    section(f"FINDINGS — {len(CATALOGUE)}")
    print(f"  {'library':<20} {'component':<38} {'span':<10} {'status':<22} check")
    print("  " + "-" * 118)
    unspanned = []
    for e in sorted(CATALOGUE, key=lambda x: -(x.span_years or 0)):
        # Read, never parsed. Three wrong renderings came from recovering these from prose.
        if e.span_years is None:
            unspanned.append(e.library)
            span = "NO SPAN"
        else:
            span = f"{e.span_years:.1f}y"
        print(f"  {e.library:<20} {e.component[:37]:<38} {span:<10} "
              f"{e.status:<22} {e.check or '(none)'}")
    if unspanned:
        raise SystemExit(
            f"\n  ERROR: {unspanned} carry no span_years. A missing measurement is an "
            f"error, not a dash — see tools/state.py's docstring."
        )

    # ------------------------------------------------------------- integrity
    section("LEDGER INTEGRITY")
    keys = {f"{e.library}|{e.component}" for e in CATALOGUE}
    withdrawn = {w.key for w in WITHDRAWALS}
    missing = [k for k in ESTABLISHED if k not in keys and k not in withdrawn]
    unrecorded = sorted(keys - set(ESTABLISHED))
    unranged = [e.library for e in CATALOGUE if e.affected_versions == "not yet ranged"]
    no_evidence = [e.library for e in CATALOGUE if not (ROOT / e.evidence).exists()]

    # Declared by the entry, then confirmed to exist by import — not grepped for.
    import unstated

    uncovered = sorted(e.library for e in CATALOGUE if e.check is None)
    dangling = sorted(
        f"{e.library}->{e.check}" for e in CATALOGUE
        if e.check and not callable(getattr(unstated, e.check, None))
    )
    def disagrees(e) -> bool:
        """The fields and the prose must say the same thing, or one of them is stale."""
        prose_says_open = e.resolved_in.strip().lower().startswith(
            ("not resolved", "unknown"))
        if (e.resolution == "open") != prose_says_open:
            return True
        if e.resolution in ("partial", "fixed") and not e.resolved_version:
            return True
        if e.resolution == "open" and e.resolved_version:
            return True
        return e.resolution not in e.RESOLUTIONS

    inconsistent = sorted(e.library for e in CATALOGUE if disagrees(e))
    rows = [
        ("established findings (append-only ledger)", len(ESTABLISHED), None),
        ("present in CATALOGUE", len(keys), None),
        ("lawfully withdrawn", len(WITHDRAWALS), None),
        ("VANISHED WITHOUT A WITHDRAWAL", len(missing), missing),
        ("catalogued but not in the ledger", len(unrecorded), unrecorded),
        ("entries with no measured version range", len(unranged), unranged),
        ("entries whose evidence file is missing", len(no_evidence), no_evidence),
        ("entries with no check (statistical findings)", len(uncovered), uncovered),
        ("entries naming a check that does not exist", len(dangling), dangling),
        ("entries whose fields disagree with their prose", len(inconsistent), inconsistent),
    ]
    for label, n, detail in rows:
        problem = ("VANISHED" in label or "not in the ledger" in label
                   or "evidence file is missing" in label or "no measured" in label
                   or "does not exist" in label or "disagree" in label)
        flag = "  <-- PROBLEM" if problem and n else ""
        print(f"  {label:<44} {n}{flag}")
        if detail:
            print(f"      {detail}")

    # ------------------------------------------------------------- held open
    section(f"HELD OPEN — {len(HELD_OPEN)} awaiting the owner's decision")
    if not HELD_OPEN:
        print("  (none)")
    for key, argument in HELD_OPEN:
        print(f"  {key}")
        print(f"      {argument[:150]}{'...' if len(argument) > 150 else ''}")

    # ----------------------------------------------------------------- tests
    section("TESTS")
    if args.run_tests:
        out = sh(sys.executable, "-m", "pytest", "-q")
        line = [l for l in out.splitlines() if "passed" in l or "failed" in l]
        print(f"  {line[-1] if line else 'could not parse pytest output'}")
    else:
        out = sh(sys.executable, "-m", "pytest", "--collect-only", "-q")
        m = re.search(r"(\d+) tests? collected", out)
        if not m:
            # pytest's own output format, not prose — but a count that degrades to "?"
            # is the same silent-wrong-answer shape as the span that degraded to "—".
            raise SystemExit(
                "  ERROR: could not read a test count from pytest. Output was:\n"
                + "\n".join(f"    {l}" for l in out.splitlines()[-8:])
            )
        print(f"  {m.group(1)} tests collected  (--run-tests to execute them)")

    # ----------------------------------------------------------- working tree
    section("WORKING TREE")
    if dirty:
        print(f"  {len(dirty.splitlines())} uncommitted change(s) — NOT yet in git history:")
        for line in dirty.splitlines()[:20]:
            print(f"      {line}")
    else:
        print("  clean — everything is committed")

    # ----------------------------------------------------------------- delta
    if args.since:
        section(f"CHANGED SINCE {args.since}")
        before = catalogue_at(args.since)
        if before is None:
            print(f"  could not load the catalogue at {args.since} "
                  f"(the package may not import there); file diff only")
        else:
            was_cat, was_est, was_wd, was_held = before
            gone_cat = sorted(was_cat - keys)
            gone_est = sorted(was_est - set(ESTABLISHED))
            gone_held = sorted(was_held - {k for k, _ in HELD_OPEN})
            added_cat = sorted(keys - was_cat)

            if gone_cat or gone_est:
                print()
                print("  ██████████████████████████████████████████████████████████████")
                print("  ██  FINDINGS WERE REMOVED. Rule 1. This needs the owner's   ██")
                print("  ██  explicit approval and a Withdrawal record.              ██")
                print("  ██████████████████████████████████████████████████████████████")
                for k in gone_cat:
                    print(f"      GONE FROM CATALOGUE : {k}")
                for k in gone_est:
                    print(f"      GONE FROM LEDGER    : {k}   <-- the record itself")
                print()
            else:
                print("  findings removed : 0")
            print(f"  findings added   : {len(added_cat)}" +
                  (f"  {added_cat}" if added_cat else ""))
            if gone_held:
                print(f"  held-open items removed : {gone_held}  <-- were these decided?")

        stat = sh("git", "diff", "--numstat", f"{args.since}..HEAD")
        if stat:
            print("\n  files changed (git, +added/-removed lines):")
            total_minus = 0
            for line in stat.splitlines():
                parts = line.split("\t")
                if len(parts) == 3:
                    plus, minus, path = parts
                    total_minus += int(minus) if minus.isdigit() else 0
                    print(f"      +{plus:<6} -{minus:<6} {path}")
            print(f"\n  {total_minus} line(s) removed in total — "
                  f"`git diff {args.since}..HEAD | grep '^-'` to read every one")
        deleted = sh("git", "diff", "--diff-filter=D", "--name-only", f"{args.since}..HEAD")
        if deleted:
            print(f"\n  FILES DELETED: {deleted.splitlines()}")

    print()
    return 1 if (missing or unrecorded or no_evidence or dangling or inconsistent) else 0


if __name__ == "__main__":
    raise SystemExit(main())
